# Lab 3: Math libraries

Welcome to this lab on the Python Standsard Library! In this assignment, you'll have the opportunity to apply your knowledge on advanced uses of data types and collections, as well as using or creating modules. We'll tackle real-world scenarios, enhancing your skills in writing robust and error-resistant code.

How to navigate the lab:

* For some exercises, you will need to fill in the blanks by adding the correct sentences or code. Look for ## YOUR CODE HERE.
* In certain sections, you are required to explain why the code behaves in specific ways. Identify these with a ‚ùìüí¨‚ùì mark.
* In some parts, you will need to write a piece of code entirely on your own. Look for "üíªüíªYOUR CODE HERE:"

## Exploring Weather Data

In this task, we will be exploring a dataset containing weather information from Australia. The dataset includes details such as the date, rainfall, cloud coverage, and temperature recorded at different locations across the country. Our goal is to analyse this data and answer some questions. Make sure to use modules (Python's and your own) and exception handling.

**Your data:**

In [1]:
Year = [2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 
         2009, 2009, 2009, 2009, 2009, 2009, 2009, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 
         2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010]
Month = [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 
         1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12]
Day   = [12, 19,  5, 22, 20, 28, 25,  5, 31, 23, 20, 11, 15,  2,  5, 11, 15, 13, 27,  2, 28, 29, 30, 29, 
         15,  9, 28, 15,  9, 21,  1, 26, 13, 21, 22,  7,  7, 15, 15, 28, 24,  6,  4, 25, 30,  1, 30, 27]
Rainfall_mm = [ 0.0, 0.0, 0.0, 0.0, 3.0, 0.2, 3.2, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.6, 0.8, 4.8, 0.0, 0.0, 0.0, 1.4, 0.0, 0.0, 0.0, 0.0, 
               12.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 2.2, 0.0, 5.6, 0.0, 0.2, 0.2, 0.0, 0.8, 0.0, 0.0, 0.0, 1.6, 0.6, 0.0]
Temp = [36.5, 34.4, 24.9, 36.2, 19.7, 21.9,  9.4, 24.6, 15.9, 19.6, 7.9, 15.2, 10.2, 15.4, 13.3, 13.0, 16.5, 15.4, 18.2, 10.9, 34.9, 32.0, 26.8, 32.7, 
        28.0, 35.3, 26.4, 28.9, 23.9, 21.8, 21.2, 27.9, 22.7, 16.5, 10.9, 8.9, 13.8, 14.2,  8.7, 12.7, 20.1, 16.1, 20.8, 20.8, 28.4, 19.5, 19.0, 24.7]
Cloud_Fraction = [0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 8.0, 0.0, 0.0, 0.0, 8.0, 6.0, 8.0, 6.0, 6.0, 8.0, 0.0, 0.0, 0.0, 
                  8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0, 1.0, 2.0, 0.0, 0.0, 8.0, 2.0, 0.0, 0.0, 0.0, 
                  8.0, 8.0, 0.0, 5.0, 0.0, 1.0, 2.0, 0.0, 8.0, 0.0]

### Task 1: Find the months with the highest and lowest average rainfall

This question requires you to analyse the rainfall data month by month and identify which months have the highest and lowest average rainfall. Understanding this can provide valuable insights into the seasonal patterns of rainfall in different regions of Australia.

In [2]:
# How the indexes or values look like:
# month_indexes = [0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]
# month_name    = [1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12] || 1 = January, 2 = February, ...
# new_index     = [0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,  9, 10, 10, 11, 11, 
#                 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23]
# total_rainfall= [0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]

total_rainfall = [0] * 12 # To store the rainfall per month 
num_observations = [0] * 12 # Number of observations per month 

# Iterate over the data
for year, month, rainfall in zip(Year, Month, Rainfall_mm):
    # Convert year and month to an index
    new_index = (year - 2009) * 12 + (month - 1)
    #print(year, month, rainfall, new_index)
    # Add the rainfall to the total for that month
    total_rainfall[new_index % 12] += rainfall
    # Increment the number of observations for that month
    num_observations[new_index % 12] += 1

In [3]:
# Calculate the average rainfall for each month
rain_per_month = zip(total_rainfall, num_observations)
#print(list(rain_per_month))
average_rainfall = [round(tot/num,2) for tot, num in rain_per_month]
print(average_rainfall)

# Find the month with the highest average rainfall
max_rainfall = max(average_rainfall)
max_month = average_rainfall.index(max_rainfall) + 1  # Adding 1 to convert index into month number
print(max_month)

# Find the month with the lowest average rainfall
min_rainfall = min(average_rainfall)
min_month = average_rainfall.index(min_rainfall) + 1
print(min_month)

[3.1, 0.0, 0.8, 0.8, 0.05, 1.05, 1.55, 1.5, 0.2, 0.35, 0.4, 0.15]
1
2

‚ùìüí¨‚ùì Q1: Which is the month with the highest average rainfail? How much did it rain?

**Answer**: January, 3.1

### Task 2: Season information 

Calculate the average temperature, rainfall and cloud fraction per season. You can follow this calendar: 

    Spring:  Begins on Sunday, September 1, and ends on Saturday, November 30.
    Summer:  Begins on Friday, December 1, and will end on Wednesday, February 29, 2024.
    Autumn:  Begins on Friday, March 1, 2024, and ends on Friday, May 31, 2024.
    Winter: Begins on Saturday, June 1st, and ends on Saturday, August 31st.

(extracted from [here. ](https://www.calendarr.com/australia/seasons-of-the-year-in-australia/))

üíªüíªYOUR CODE HERE:

In [4]:
import pandas as pd
data = {'Year':Year, 'Month':Month, 'Day':Day, 'Rain':Rainfall_mm, 'Temp':Temp, 'Cloud':Cloud_Fraction}
df = pd.DataFrame(data=data)

def label_season(row):
    if row['Month'] in (12, 1, 2):
        return 'Summer'
    if row['Month'] in (3, 4, 5):
        return 'Autumn'
    if row['Month'] in (6, 7, 8):
        return 'Winter'
    if row['Month'] in (9, 10, 11):
        return 'Spring'
    raise ValueError('Months must be between 1 and 12')
    
df['Season'] = df.apply(label_season, axis=1)
df_season_mean = df.groupby(by='Season').mean()[['Rain','Temp','Cloud']].round(2)
df_season_mean

        Rain   Temp  Cloud
Season
Autumn  0.55  20.42   1.92
Spring  0.32  21.13   1.33
Summer  1.08  29.48   1.33
Winter  1.37  12.02   5.00

### Task 3: Floading time
- ‚ùìüí¨‚ùì Q1: Assume that there is flooding when the average rainfall in a season is equal to or greater than 1.0. In which seasons are there floodings?
- ‚ùóüí¨‚ùó__A1: Summer and Winter__

- ‚ùìüí¨‚ùì Q2: Simulate a scenario where rainfall increases by 10% for 10 randomly selected records. Which is the season with the most floodings? For this question, set the random seed to 1234.
- ‚ùóüí¨‚ùó__A2: Winter__

üíªüíªYOUR CODE HERE:

In [5]:
## SIMULATE 10% MORE RAIN FOR 10 MONTHS
import random
random.seed(1234)
sim_rain = Rainfall_mm.copy()
for x in random.choices(range(len(Rainfall_mm)), k=10): # Pick 10 random indices
    sim_rain[x] = sim_rain[x] * 1.1 # Multiply by 1.1 => 10 % increase

sim_data = {'Year':Year, 'Month':Month, 'Day':Day, 'Rain':sim_rain, 'Temp':Temp, 'Cloud':Cloud_Fraction}
df_sim = pd.DataFrame(data=sim_data)
df_sim['Season'] = df_sim.apply(label_season, axis=1)
df_sim_mean = df_sim.groupby(by='Season').mean()[['Rain','Temp','Cloud']].round(2)
df_sim_mean

        Rain   Temp  Cloud
Season
Autumn  0.58  20.42   1.92
Spring  0.33  21.13   1.33
Summer  1.09  29.48   1.33
Winter  1.41  12.02   5.00

### Task 4: Stars 

‚ùìüí¨‚ùì Q4: Assume that there is a starry sky when the cloud fraction is 0. In which year people saw the most stars? 
- ‚ùóüí¨‚ùó__A4: 2009 (15 times with cloud fraction = 0)__

üíªüíªYOUR CODE HERE:

In [8]:
df_starry_years = df[['Year','Month','Day','Cloud']]
df_starry_years = df_starry_years[df_starry_years['Cloud'] == 0.0].groupby(by='Year').count()
df_starry_years = df_starry_years.rename({'Cloud': 'Starry moments'}, axis=1)
df_starry_years[['Starry moments']]

      Starry moments
Year
2009              15
2010              13

### Extra (this part will not be graded)  

Now you have a user interacting with the data. Imagine that the user wants to know the average temperature and rain fall given a season, in other words, the user inputs e.g. "Winter" and the programme outputs the temperature and rain fall. Write your implementation for this task.

üíªüíªYOUR CODE HERE:

In [29]:
season = input("Input season (Winter|Spring|Summer|Autumn)")
try:
    res = df_season_mean[['Rain','Temp']].loc[season.capitalize()].to_dict()
    print(f"Average temperature: {res['Temp']}¬∞C, average rain fall: {res['Rain']} mm.")
except KeyError as ke:
    print("That doesn't seem like a season, please run the cell again")

Input season (Winter|Spring|Summer|Autumn) summer

Average temperature: 29.48¬∞C, average rain fall: 1.08 mm.